CREATE TABLE IF NOT EXISTS users (
    id BIGINT  GENERATED by default as identity primary key,
    name varchar(128),
    email varchar(128) NOT NULL
);

CREATE TABLE IF NOT EXISTS requests (
    id BIGINT  GENERATED by default as identity primary key,
    description varchar(2048),
    requestor_id INTEGER REFERENCES users
);

CREATE TABLE IF NOT EXISTS items (
    id BIGINT GENERATED by default as identity primary key,
    name varchar(256) NOT NULL,
    description varchar(2048),
    is_available boolean,
    owner_id integer references users,
    request_id integer references requests
);

CREATE TABLE IF NOT EXISTS bookings (
    id BIGINT  GENERATED by default as identity primary key,
    start_date TIMESTAMP WITHOUT TIME ZONE,
    end_date TIMESTAMP WITHOUT TIME ZONE,
    item_id INTEGER REFERENCES items,
    booker_id INTEGER REFERENCES users,
    status VARCHAR(64)
);

CREATE TABLE IF NOT EXISTS comments (
    id BIGINT  GENERATED by default as identity primary key,
    text varchar(2048),
    item_id INTEGER REFERENCES items,
    author_id INTEGER REFERENCES users,
    created TIMESTAMP WITHOUT TIME ZONE default current_timestamp
);