create table if not exists users (
    id bigint generated by default as identity primary key,
    name varchar(128),
    email varchar(128) not null
);

create table if not exists requests (
    id bigint  generated by default as identity primary key,
    description varchar(2048),
    requestor_id bigint references users(id),
    created timestamp without time zone
);

create table if not exists items (
    id bigint generated by default as identity primary key,
    name varchar(256) not null,
    description varchar(2048),
    is_available boolean,
    owner_id bigint references users(id),
    request_id bigint references requests(id)
);

create table if not exists bookings (
    id bigint  generated by default as identity primary key,
    start_date timestamp without time zone,
    end_date timestamp without time zone,
    item_id bigint references items(id),
    booker_id bigint references users(id),
    status varchar(64)
);

create table if not exists comments (
    id bigint  generated by default as identity primary key,
    text varchar(2048),
    item_id bigint references items(id),
    author_id bigint references users(id),
    created timestamp without time zone default current_timestamp
);